### ISSUE TITLE
Pantalla Inicio de Sesión: Colocar mensaje correcto de error para datos inválidos. 

### ISSUE THREAD

**Issue by zchacon** [elinarezv/app_gis_usb_ven#1]
1.Error: Mensaje correcto de error para datos inválidos. Sucede cuando se coloca contraseña invalida. “Error inicio de sesión” [Object object]

**Comment by zchacon** [comment]
Por seguridad no se debe informar que es contraseña invalida, Coloquemos sólo "Error de inicio de sesión: Datos inválidos".

**Comment by elinarezv** [comment]
Este issue debería estar corregido, revisa la apk que te envié. Saludos
