### ISSUE TITLE
Error: en Crear cuenta, con un correo que ya existe.

### ISSUE THREAD

**Issue by zchacon** [elinarezv/app_gis_usb_ven#2]
2.Error: En registrar la cuenta, con un correo que ya existe. Se queda como colgado, se activa “Términos y condiciones” y se desactiva el botón “Crear Cuenta”.. Se debe corregir esos cambios automáticos y debe indicar mensaje que el usuario ya existe..

**Comment by elinarezv** [comment]
Este issue debería estar corregido, revisa la apk que te envié. Saludos

**Comment by zchacon** [comment]
Está corregido Elio, sólo por favor modificar el mensaje. "Ha habido un problema...." cambiar la palabra "habido" por "ocurrido"  -> "Ha ocurrido un problema... "
