### ISSUE TITLE
Error. Inicio de sesión con datos vacíos

### ISSUE THREAD

**Issue by zchacon** [elinarezv/app_gis_usb_ven#7]
No muestra mensaje adecuado, indica un mensaje de .... : login: 500 Internal Server Error

**Comment by zchacon** [comment]
El campo correo electrónico no valida formato de correo. 

Validar que esten llenos ambos campos para corregir el error.

**Comment by elinarezv** [comment]
Este issue debería estar corregido, revisa la apk que te envié. Saludos
